/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apps\web\public\model\Joe_animated.glb --transform 
Files: apps\web\public\model\Joe_animated.glb [58.4MB] > C:\Users\igorc\Desktop\Development\fitrah\Joe_animated-transformed.glb [2.34MB] (96%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Joe_animated(props) {
  const { pose = 'idle', ...groupProps } = props
  const group = React.useRef()
  const { scene, animations } = useGLTF('/model/Joe_animated-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    const activeAction = actions[pose] ?? actions.idle

    if (!activeAction) {
      return
    }

    Object.entries(actions).forEach(([name, action]) => {
      if (name !== pose) {
        action?.fadeOut(0.2)
      }
    })

    activeAction.reset().fadeIn(0.2).play()

    return () => {
      activeAction.fadeOut(0.2)
    }
  }, [actions, pose])

  return (
    <group ref={group} {...groupProps} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig7Hips} />
        </group>
        <skinnedMesh name="Ch33_Belt" geometry={nodes.Ch33_Belt.geometry} material={materials.Ch33_body} skeleton={nodes.Ch33_Belt.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Ch33_Body" geometry={nodes.Ch33_Body.geometry} material={materials.Ch33_body} skeleton={nodes.Ch33_Body.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Ch33_Eyelashes" geometry={nodes.Ch33_Eyelashes.geometry} material={materials.Ch33_hair} skeleton={nodes.Ch33_Eyelashes.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Ch33_Hair" geometry={nodes.Ch33_Hair.geometry} material={materials.Ch33_hair} skeleton={nodes.Ch33_Hair.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Ch33_Pants" geometry={nodes.Ch33_Pants.geometry} material={materials.Ch33_body} skeleton={nodes.Ch33_Pants.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Ch33_Shirt" geometry={nodes.Ch33_Shirt.geometry} material={materials.Ch33_body} skeleton={nodes.Ch33_Shirt.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Ch33_Shoes" geometry={nodes.Ch33_Shoes.geometry} material={materials.Ch33_body} skeleton={nodes.Ch33_Shoes.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Ch33_Suit" geometry={nodes.Ch33_Suit.geometry} material={materials.Ch33_body} skeleton={nodes.Ch33_Suit.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Ch33_Tie" geometry={nodes.Ch33_Tie.geometry} material={materials.Ch33_body} skeleton={nodes.Ch33_Tie.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/Joe_animated-transformed.glb')
