/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apps/web/public/model/platform.glb --transform --output apps/web/components/Platform.jsx 
Files: apps/web/public/model/platform.glb [2.92MB] > C:\Users\igorc\Desktop\Development\fitrah\apps\web\components\platform-transformed.glb [188.74KB] (94%)
Author: djechopetro (https://sketchfab.com/djechopetro)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medievalsci-fi-platform-corner-square-592f938156e94f2f87a9febf3a76f5d8
Title: Medieval/Sci-Fi Platform - Corner Square
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model/platform-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.platformPrefabCorner_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/model/platform-transformed.glb')
